namespace NextMovie.Api.Domain;

/// <summary>
/// A film genre, e.g. Science Fiction.
/// </summary>
/// <remarks>
/// Unlike <see cref="Movie"/>, this uses TMDb's identifier directly as its
/// primary key. Genres are a small, fixed, slow-moving reference set synced from
/// a single source, so the natural key carries none of the risk it would on
/// Movie: there is no scenario where NextMovie invents a genre TMDb lacks, and
/// the well-known ids (28 = Action, 878 = Science Fiction) are stable.
/// </remarks>
public class Genre
{
    /// <summary>TMDb's genre identifier. Assigned by TMDb, never generated by the database.</summary>
    public required int Id { get; init; }

    /// <summary>Display name, e.g. <c>Science Fiction</c>.</summary>
    public required string Name { get; set; }

    /// <summary>Films in this genre.</summary>
    public ICollection<Movie> Movies { get; init; } = [];
}
