/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Reports whether the API process is running and serving requests.
         */
        get: operations["GetHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/movies/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search films by title
         * @description Searches TMDb by title, stores the results in the NextMovie catalogue, and returns them ranked by relevance.
         */
        get: operations["SearchMovies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/movies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a film
         * @description Returns a film from the NextMovie catalogue, enriching it from TMDb when its details are missing or stale.
         */
        get: operations["GetMovieDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account
         * @description Creates a new account with an email and password, and returns an access token and refresh token for the new session.
         */
        post: operations["RegisterUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in
         * @description Exchanges an email and password for an access token and refresh token. Repeated failures temporarily lock the account.
         */
        post: operations["LoginUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh a session
         * @description Exchanges a refresh token for a new access token and a new refresh token. The presented token is revoked; presenting it again ends the session.
         */
        post: operations["RefreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out
         * @description Revokes the session the refresh token belongs to. Always succeeds, whether or not the token was still valid.
         */
        post: operations["LogoutUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in with Google
         * @description Verifies a Google ID token and returns a NextMovie session, creating an account or linking the Google identity to an existing one.
         */
        post: operations["SignInWithGoogle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the signed-in user's profile
         * @description Returns the profile of the account the access token belongs to.
         */
        get: operations["GetCurrentUser"];
        /**
         * Update the signed-in user's profile
         * @description Replaces the editable parts of the profile. Fields omitted from the request are cleared.
         */
        put: operations["UpdateCurrentUser"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/movies/{id}/rating": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Rate a film
         * @description Records the signed-in user's rating of a film, on a 0.5–5.0 half-star scale. Rating a film also records that it was watched.
         */
        put: operations["RateMovie"];
        post?: never;
        /**
         * Remove a rating
         * @description Removes the signed-in user's rating of a film. The film stays in their watch history.
         */
        delete: operations["UnrateMovie"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the signed-in user's ratings
         * @description Returns rated films, most recently rated first.
         */
        get: operations["GetMyRatings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The account a session belongs to. */
        AuthenticatedUser: {
            /**
             * Format: uuid
             * @description NextMovie user identifier.
             */
            id: string;
            /** @description Email address, as the user entered it. */
            email: string;
            /** @description Name to show in the UI. */
            displayName: string;
            /** @description Avatar URL, when one is set. */
            profileImageUrl: null | string;
        };
        /** @description A newly established session. */
        AuthenticationResponse: {
            /** @description Bearer token for API calls. Send as `Authorization: Bearer {token}`. */
            accessToken: string;
            /**
             * Format: date-time
             * @description When the access token stops being accepted.
             */
            accessTokenExpiresAt: string;
            /** @description Opaque token used to obtain a new access token. Store it as securely as a password. */
            refreshToken: string;
            /**
             * Format: date-time
             * @description When the refresh token stops being exchangeable.
             */
            refreshTokenExpiresAt: string;
            /** @description The signed-in account. */
            user: components["schemas"]["AuthenticatedUser"];
        };
        /** @description Response body returned by the health endpoint. */
        HealthResponse: {
            /** @description Always `healthy` when the process is serving requests. */
            status: string;
            /** @description Informational assembly version of the running build. */
            version: string;
            /**
             * Format: date-time
             * @description Server time at which the probe was answered.
             */
            timestampUtc: string;
        };
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        /** @description Credentials presented at sign-in. */
        LoginUserRequest: {
            /** @description Email address the account was registered with. Case-insensitive. */
            email: null | string;
            /** @description The account's password. */
            password: null | string;
        };
        /** @description The session to end. */
        LogoutUserRequest: {
            /** @description The refresh token held by the client signing out. */
            refreshToken: null | string;
        };
        /** @description Everything the catalogue holds about a film. */
        MovieDetails: {
            /**
             * Format: uuid
             * @description NextMovie identifier.
             */
            id: string;
            /**
             * Format: int32
             * @description TMDb identifier, exposed for attribution and deep links.
             */
            tmdbId: number;
            /** @description Display title. */
            title: string;
            /** @description Title in the original language, when it differs. */
            originalTitle: null | string;
            /** @description Synopsis, when TMDb has one. */
            overview: null | string;
            /** @description Relative TMDb poster path; combine with a TMDb image base URL to render. */
            posterPath: null | string;
            /** @description Relative TMDb backdrop path. */
            backdropPath: null | string;
            /**
             * Format: date
             * @description Release date, when known.
             */
            releaseDate: null | string;
            /**
             * Format: int32
             * @description Runtime in minutes. Null when TMDb does not know it.
             */
            runtime: null | number;
            /**
             * Format: double
             * @description TMDb community rating 0–10. Null when the film has no votes.
             */
            averageRating: null | number;
            /**
             * Format: double
             * @description TMDb popularity score. Only meaningful compared against other films.
             */
            popularity: null | number;
            /** @description ISO 639-1 code of the original language. */
            language: null | string;
            /** @description TMDb release status, e.g. `Released`. */
            status: null | string;
            /** @description Genre names, alphabetically. */
            genres: string[];
        };
        /** @description The signed-in user's rating of a film. */
        MovieRating: {
            /**
             * Format: uuid
             * @description The film rated.
             */
            movieId: string;
            /**
             * Format: double
             * @description 0.5 to 5.0, in half-stars.
             */
            rating: number;
            /**
             * Format: date-time
             * @description When the rating was last set or changed.
             */
            ratedAt: string;
        };
        /** @description Summary view of a film. */
        MovieSummary: {
            /**
             * Format: uuid
             * @description NextMovie identifier. Stable, and the one clients should store.
             */
            id: string;
            /**
             * Format: int32
             * @description TMDb identifier, exposed for attribution and deep links.
             */
            tmdbId: number;
            /** @description Display title. */
            title: string;
            /** @description Synopsis, when TMDb has one. */
            overview: null | string;
            /** @description Relative TMDb poster path; combine with a TMDb image base URL to render. */
            posterPath: null | string;
            /**
             * Format: date
             * @description Release date, when known.
             */
            releaseDate: null | string;
            /**
             * Format: double
             * @description TMDb community rating 0–10. Null when the film has no votes.
             */
            averageRating: null | number;
            /** @description Genre names, alphabetically. */
            genres: string[];
        };
        /** @description A page of the user's ratings. */
        MyRatingsResponse: {
            /** @description Rated films, most recently rated first. */
            ratings: components["schemas"]["RatedMovie"][];
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
        };
        /** @description A film the user has rated. */
        RatedMovie: {
            /**
             * Format: uuid
             * @description NextMovie identifier.
             */
            movieId: string;
            /** @description Display title. */
            title: string;
            /** @description Relative TMDb poster path. */
            posterPath: null | string;
            /**
             * Format: date
             * @description Release date, when known.
             */
            releaseDate: null | string;
            /**
             * Format: double
             * @description 0.5 to 5.0, in half-stars.
             */
            rating: number;
            /**
             * Format: date-time
             * @description When the rating was last set or changed.
             */
            ratedAt: string;
        };
        /** @description A rating to record. */
        RateMovieRequest: {
            /**
             * Format: double
             * @description 0.5 to 5.0, in half-stars.
             */
            rating: null | number;
        };
        /** @description The refresh token to exchange. */
        RefreshSessionRequest: {
            /** @description The refresh token issued by register, login, or a previous refresh. */
            refreshToken: null | string;
        };
        /** @description Details needed to create an account. */
        RegisterUserRequest: {
            /** @description Email address. Must be unique, ignoring case. */
            email: null | string;
            /** @description Name to show in the UI. */
            displayName: null | string;
            /** @description Chosen password. See PasswordPolicy for the rules. */
            password: null | string;
        };
        /** @description A page of search results. */
        SearchMoviesResponse: {
            /**
             * Format: int32
             * @description The page returned.
             */
            page: number;
            /**
             * Format: int32
             * @description Total pages available for this query.
             */
            totalPages: number;
            /**
             * Format: int32
             * @description Total matching films.
             */
            totalResults: number;
            /** @description Films on this page, ordered by relevance. */
            results: components["schemas"]["MovieSummary"][];
        };
        /** @description The Google ID token to sign in with. */
        SignInWithGoogleRequest: {
            /** @description An ID token obtained by the client from Google. */
            idToken: null | string;
        };
        /** @description The new state of the editable profile. */
        UpdateCurrentUserRequest: {
            /** @description Name to show in the UI. Required. */
            displayName: null | string;
            /** @description Absolute http or https avatar URL. Omit or send null to clear it. */
            profileImageUrl: null | string;
        };
        /** @description A user's own profile. */
        UserProfileResponse: {
            /**
             * Format: uuid
             * @description NextMovie user identifier.
             */
            id: string;
            /** @description Email address, as the user entered it. */
            email: string;
            /** @description Name shown in the UI. */
            displayName: string;
            /** @description Avatar URL, when one is set. */
            profileImageUrl: null | string;
            /**
             * Format: date-time
             * @description When the account was created.
             */
            createdAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    SearchMovies: {
        parameters: {
            query?: {
                title?: string;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchMoviesResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    GetMovieDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovieDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    RegisterUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterUserRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    LoginUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginUserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    RefreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshSessionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    LogoutUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutUserRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    SignInWithGoogle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInWithGoogleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    UpdateCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCurrentUserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    RateMovie: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RateMovieRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovieRating"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    UnrateMovie: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetMyRatings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyRatingsResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
