/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Reports whether the API process is running and serving requests.
         */
        get: operations["GetHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/movies/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search films by title
         * @description Searches TMDb by title, stores the results in the NextMovie catalogue, and returns them ranked by relevance.
         */
        get: operations["SearchMovies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account
         * @description Creates a new account with an email and password, and returns an access token and refresh token for the new session.
         */
        post: operations["RegisterUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in
         * @description Exchanges an email and password for an access token and refresh token. Repeated failures temporarily lock the account.
         */
        post: operations["LoginUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh a session
         * @description Exchanges a refresh token for a new access token and a new refresh token. The presented token is revoked; presenting it again ends the session.
         */
        post: operations["RefreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out
         * @description Revokes the session the refresh token belongs to. Always succeeds, whether or not the token was still valid.
         */
        post: operations["LogoutUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The account a session belongs to. */
        AuthenticatedUser: {
            /**
             * Format: uuid
             * @description NextMovie user identifier.
             */
            id: string;
            /** @description Email address, as the user entered it. */
            email: string;
            /** @description Name to show in the UI. */
            displayName: string;
            /** @description Avatar URL, when one is set. */
            profileImageUrl: null | string;
        };
        /** @description A newly established session. */
        AuthenticationResponse: {
            /** @description Bearer token for API calls. Send as `Authorization: Bearer {token}`. */
            accessToken: string;
            /**
             * Format: date-time
             * @description When the access token stops being accepted.
             */
            accessTokenExpiresAt: string;
            /** @description Opaque token used to obtain a new access token. Store it as securely as a password. */
            refreshToken: string;
            /**
             * Format: date-time
             * @description When the refresh token stops being exchangeable.
             */
            refreshTokenExpiresAt: string;
            /** @description The signed-in account. */
            user: components["schemas"]["AuthenticatedUser"];
        };
        /** @description Response body returned by the health endpoint. */
        HealthResponse: {
            /** @description Always `healthy` when the process is serving requests. */
            status: string;
            /** @description Informational assembly version of the running build. */
            version: string;
            /**
             * Format: date-time
             * @description Server time at which the probe was answered.
             */
            timestampUtc: string;
        };
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        /** @description Credentials presented at sign-in. */
        LoginUserRequest: {
            /** @description Email address the account was registered with. Case-insensitive. */
            email: null | string;
            /** @description The account's password. */
            password: null | string;
        };
        /** @description The session to end. */
        LogoutUserRequest: {
            /** @description The refresh token held by the client signing out. */
            refreshToken: null | string;
        };
        /** @description Summary view of a film. */
        MovieSummary: {
            /**
             * Format: uuid
             * @description NextMovie identifier. Stable, and the one clients should store.
             */
            id: string;
            /**
             * Format: int32
             * @description TMDb identifier, exposed for attribution and deep links.
             */
            tmdbId: number;
            /** @description Display title. */
            title: string;
            /** @description Synopsis, when TMDb has one. */
            overview: null | string;
            /** @description Relative TMDb poster path; combine with a TMDb image base URL to render. */
            posterPath: null | string;
            /**
             * Format: date
             * @description Release date, when known.
             */
            releaseDate: null | string;
            /**
             * Format: double
             * @description TMDb community rating 0–10. Null when the film has no votes.
             */
            averageRating: null | number;
            /** @description Genre names, alphabetically. */
            genres: string[];
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
        };
        /** @description The refresh token to exchange. */
        RefreshSessionRequest: {
            /** @description The refresh token issued by register, login, or a previous refresh. */
            refreshToken: null | string;
        };
        /** @description Details needed to create an account. */
        RegisterUserRequest: {
            /** @description Email address. Must be unique, ignoring case. */
            email: null | string;
            /** @description Name to show in the UI. */
            displayName: null | string;
            /** @description Chosen password. See PasswordPolicy for the rules. */
            password: null | string;
        };
        /** @description A page of search results. */
        SearchMoviesResponse: {
            /**
             * Format: int32
             * @description The page returned.
             */
            page: number;
            /**
             * Format: int32
             * @description Total pages available for this query.
             */
            totalPages: number;
            /**
             * Format: int32
             * @description Total matching films.
             */
            totalResults: number;
            /** @description Films on this page, ordered by relevance. */
            results: components["schemas"]["MovieSummary"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    SearchMovies: {
        parameters: {
            query?: {
                title?: string;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchMoviesResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    RegisterUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterUserRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    LoginUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginUserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    RefreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshSessionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    LogoutUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutUserRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
}
