/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Reports whether the API process is running and serving requests.
         */
        get: operations["GetHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/movies/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search films by title
         * @description Searches TMDb by title, stores the results in the NextMovie catalogue, and returns them ranked by relevance.
         */
        get: operations["SearchMovies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Response body returned by the health endpoint. */
        HealthResponse: {
            /** @description Always `healthy` when the process is serving requests. */
            status: string;
            /** @description Informational assembly version of the running build. */
            version: string;
            /**
             * Format: date-time
             * @description Server time at which the probe was answered.
             */
            timestampUtc: string;
        };
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        /** @description Summary view of a film. */
        MovieSummary: {
            /**
             * Format: uuid
             * @description NextMovie identifier. Stable, and the one clients should store.
             */
            id: string;
            /**
             * Format: int32
             * @description TMDb identifier, exposed for attribution and deep links.
             */
            tmdbId: number;
            /** @description Display title. */
            title: string;
            /** @description Synopsis, when TMDb has one. */
            overview: null | string;
            /** @description Relative TMDb poster path; combine with a TMDb image base URL to render. */
            posterPath: null | string;
            /**
             * Format: date
             * @description Release date, when known.
             */
            releaseDate: null | string;
            /**
             * Format: double
             * @description TMDb community rating 0–10. Null when the film has no votes.
             */
            averageRating: null | number;
            /** @description Genre names, alphabetically. */
            genres: string[];
        };
        /** @description A page of search results. */
        SearchMoviesResponse: {
            /**
             * Format: int32
             * @description The page returned.
             */
            page: number;
            /**
             * Format: int32
             * @description Total pages available for this query.
             */
            totalPages: number;
            /**
             * Format: int32
             * @description Total matching films.
             */
            totalResults: number;
            /** @description Films on this page, ordered by relevance. */
            results: components["schemas"]["MovieSummary"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    SearchMovies: {
        parameters: {
            query?: {
                title?: string;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchMoviesResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
}
